Implement Parse and TryParse static methods on Version and Range.
adamreeve/semver.net pull request #48
Opened 2020-09-14 21:04 UTC by perfectsquircle

This theoretically satisfies issue #10. Please review and let me know if I missed anything.

2020-09-20 21:05 UTC, adamreeve requested changes
Hi, looks good, thanks for this. Just a minor fix needed for the XML comments.

I'm on the fence about using overloads of `TryParse` with and without the loose parameter, it seems like having one method that takes an optional parameter would be better for consistency but I guess this was done to keep the output parameter as the last parameter? So happy to keep that as is.

2020-09-20 21:05 UTC, adamreeve commented on src/SemVer/Version.cs
> +        /// <param name="loose">When true, be more forgiving of some invalid version specifications.</param>
The two `Version.TryParse` methods are missing XML comment docs for the result parameter.

2020-09-21 19:40 UTC, perfectsquircle commented on src/SemVer/Version.cs
> +        /// <param name="loose">When true, be more forgiving of some invalid version specifications.</param>
OK. I've pushed another commit with the missing XML docs.

2020-09-21 19:47 UTC, perfectsquircle commented
> I guess this was done to keep the output parameter as the last parameter?

Yes. The compiler wants optional arguments at the end (CS1737), however it seems that convention for TryParse is that the `out` parameter appears at the end.

2020-09-21 21:36 UTC, merged